export { default as Header } from './Header';
export * from './Header/style';
export * from './Hero';
export * from './Hero/style';
export * from './Layout';
export * from './Layout/style';
export * from './Product/components/InformationComponent';
export * from './Product/components/InformationComponent/style';
export * from './Product';
export * from './Product/style';
